#!/usr/bin/env bash

set -e

PATH=/usr/local/bin:$PATH

if [[ $1 == "app" ]]
    then packageName="com.test.myapp"
    apkPrefix="android-proj-debug"
    packageLocation=packages
    appName=$(adb -s emulator-5554 shell pm list packages \"com.test.myapp\" | sed '/tests/d')
  elif [[ $1 == "test" ]]
    then packageName="com.test.myapp.tests"
    apkPrefix="android-proj-test-debug"
    packageLocation=test-packages
    appName=$(adb -s emulator-5554 shell pm list packages \"com.test.myapp.tests\")
  else
    echo "wrong use!!"
    echo "installApk.sh app //to install app apk"
    echo "installApk.sh test //to install test apk"
    exit 1
  fi

echo "pre-install checks"
if [[ -n $appName ]]
  then
  echo "Required package is already installed. Uninstalling it."
  bash ./uninstall $1
  fi

echo "Installing.."
adb -s emulator-5554 install ../$packageLocation/$apkPrefix-${GO_DEPENDENCY_LABEL_BUILD}.apk
