#!/bin/bash
bash /usr/local/bin/adb -s emulator-5554 shell am instrument -w com.test.myapp.tests/android.test.InstrumentationTestRunner > test.log
cat test.log
failure=$(cat test.log | grep -F "FAILURES!!!")
if [[  -z $failure ]]
then
exit 0;
else
exit 1;
fi


